apiVersion: config.openservicemesh.io/v1alpha1
kind: MeshConfig
metadata:
  name: osm-mesh-config
spec:
  sidecar:
    enablePrivilegedInitContainer: false
    logLevel: error
    maxDataPlaneConnections: 0
    envoyImage: "envoyproxy/envoy-alpine@sha256:e368e254b426ef3d5e8235ee5f51c1d6534fefb1da4217fa2d5ba2eee9edbb63"
    initContainerImage: "openservicemesh/init:latest-main"
    configResyncInterval: "0s"
  traffic:
    enableEgress: false
    useHTTPSIngress: false
    enablePermissiveTrafficPolicyMode: true
  observability:
    enableDebugServer: true
    outboundPortExclusionList: []
    inboundPortExclusionList: []
    outboundIPRangeExclusionList: []
    tracing:
      enable: false
  certificate:
    serviceCertValidityDuration: 24h
