name: Windows Nightly Job
# on: 
#   workflow_run:
#     workflows: ["Windows Images"]
#     types: [completed]

on:
  push:
    branches:
      - windowsNightlyJob
env:
  CTR_REGISTRY: openservicemesh
  CTR_TAG: latest-main

jobs:
  test:
    name: Windows Cluster Nightly Job
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout v2
        uses: actions/checkout@v2
      - name: Authenticate and set context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.WINDOWS_SERVER }}
        id: setcontext
      - name: Test oc
        run: oc version --client
      - name: Setup Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Run e2es
        run: |
          make build-osm
          go test ./tests/e2e -test.v -ginkgo.v -ginkgo.progress -ginkgo.focus="\bCrossPlat\b" -test.timeout 180m -deployOnWindowsWorkers=true
      - name: Cleanup resources
        if: ${{ always() }}
        run: |
          kubectl delete service vault -n osm-system --ignore-not-found --wait
