name: Windows Nightly Job
on: 
  workflow_run:
    workflows: ["Windows Images"]
    types: [completed]

env:
  CTR_REGISTRY: openservicemesh
  CTR_TAG: latest-main

jobs:
  test:
    name: Windows Cluster Nightly Job
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout v2
        uses: actions/checkout@v2
      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
      - name: Test oc
        run: oc version --client
      - name: Setup Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Run e2es
        run: |
          make build-osm
          go test ./tests/e2e -test.v -ginkgo.v -ginkgo.progress -ginkgo.focus="\bCrossPlat\b" -test.timeout 180m -deployOnWindowsWorkers=true
      - name: Cleanup resources
        if: ${{ always() }}
        env:
          BOOKWAREHOUSE_NAMESPACE: bookwarehouse
          BOOKBUYER_NAMESPACE: bookbuyer
          BOOKSTORE_NAMESPACE: bookstore
          BOOKTHIEF_NAMESPACE: bookthief
          MESH_NAME: osm
          K8S_NAMESPACE: osm-system
          TIMEOUT: 90s
        run: |
          touch .env
          ./demo/clean-kubernetes.sh
